import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Orden from './restaurantes/orden';
import React, { useState } from 'react'

const Home = ({data}) => {

  return (

    <>
      <Head>
        <title>CafeUNIS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="/principal.css" />
      </Head>

        <header id="header">
          <h2>CafeUNIS</h2>
            <h1>¡Elije dónde!</h1>
          <nav>
            <Link href='/' className='boton_nav'>Cerrar sesion</Link>
          </nav>
        </header>

    <main id="main">
      <div id='restaurantes'>
        {data.map((res) => (
          <>
            <section className='logo-container' id={res.id}>
              <h3> {res.restaurante} </h3>
              <Link href={`/restaurantes/${res.id_2}`}>
                <Image className='imagen-restaurante' src={res.image} alt={res.id}
                width={res.imageWidth} height={res.imageHeight}/>
              </Link>
            </section>
          </>
          ))}
        </div>

        <button className='ver-cupones'>Ver cupones</button>
    </main>
    </>
  );
}

export default Home;

export async function getStaticProps() {
  const {restaurantes} = await import ("/data/data.json");//obtener los datos de los restaurantes(consulta a base de datos)
  console.log(restaurantes);//mostrar data en la consola

  return {
      props:{
          data: restaurantes,
      },
  }
}
